pipeline {
    agent any

    environment {
        WORKSPACE_DIR = "${env.WORKSPACE}"
    }

    stages {

        stage('Checkout Source') {
            steps {
                echo 'Checking out code from Git'
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/main']],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [],
                          userRemoteConfigs: [[url: 'https://github.com/Shubh-art278/MIL_Automation.git']]])
            }
        }

        stage('Run MIL Model Tests') {
            steps {
                echo 'Running MATLAB MIL model tests'
                bat """
                matlab -batch "cd('${WORKSPACE_DIR}'); addpath(genpath(pwd)); run_all_tests; exit"
                """
            }
        }

        stage('Publish Test Results') {
            steps {
                echo 'Publishing test results (if any JUnit XMLs are generated)'
                junit allowEmptyResults: true, testResults: "**/Test_Results/*.xml"
            }
        }

        stage('Archive Artifacts') {
            steps {
                echo 'Archiving artifacts generated by MATLAB'
                archiveArtifacts artifacts: "**/Artifacts/**", fingerprint: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
        success {
            echo 'Build passed!'
        }
        failure {
            echo 'Build failed. Check console output.'
        }
    }
}
